name: Windows

on: [push]

jobs:
  build:
    name: build on windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: |
        echo "Hello"
      shell: cmd
